micronaut:
  application:
    name: demoSec
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:xGqulvH^ew*O5XjiZ2XWvI2OgL5BTi}"'
  hibernate:
    hbm2ddl:
      auto: update
  datasources:
    default:
      url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
      username: ${JDBC_USER:sa}
      password: ${JDBC_PASSWORD:""}
      driverClassName: ${JDBC_DRIVER:org.h2.Driver}
  jpa:
    default:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          show_sql: true